name: deploy
on: 
  push:
    branches:
      - "main"
    paths:
      - iac/**
      - .github/workflows/deploy.yml
  workflow_dispatch:

env:
  WORKING_DIRECTORY: iac
  REMOTE_STATE_RG: adls-demo-eastus2
  REMOTE_STATE_SA: tfadlsed
  REMOTE_STATE_CONTAINER: adls-remote-state-eastus2-demo
  REMOTE_STATE_KEY: adls.terraform.tfstate
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  
permissions:
  id-token: write
  contents: read

jobs:
  plan:
      name: 'plan infrastructure'
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ${{ env.WORKING_DIRECTORY }}
      steps:
        - name: 'Checkout Repo'
          uses: actions/checkout@v2
        - name: 'Azure Login'
          uses: azure/login@v1
          with:
            tenant-id: ${{ secrets.TENANT_ID }}
            subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            client-id: ${{ secrets.CLIENT_ID }}
        - name: 'Get Deployer Secrets'
          id: get-deployer-secret
          uses: azure/get-keyvault-secrets@v1
          with:
            keyvault: ${{ secrets.DEPLOYER_KEY_VAULT }}
            secrets: 'adls2-demo-eastus2-deployer, tfadls2ed-access-key'
        - name: 'Setup Terraform'
          uses: hashicorp/setup-terraform@v1
        - name: 'Terraform Init'
          env: 
            TF_CLI_ARGS_init: "-backend-config='resource_group_name=${{env.REMOTE_STATE_RG}}' -backend-config='storage_account_name=${{env.REMOTE_STATE_SA}}' -backend-config='container_name=${{env.REMOTE_STATE_CONTAINER}}' -backend-config='key=${{env.REMOTE_STATE_KEY}}'"
            ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfadls2ed-access-key }}
          run: terraform init
        - name: 'Terraform Validate'
          run: terraform validate
        - name: 'Terraform Plan'
          env:        
            ARM_CLIENT_SECRET: ${{ steps.get-deployer-secret.outputs.adls2-demo-eastus2-deployer }}
            ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfadls2ed-access-key }}
            TF_VAR_admin_user_principal_name: ${{ secrets.WORKLOAD_ADMIN_UPN }}
          run: terraform plan -out="./workload.tfplan"
        - name: 'Upload Plan'
          uses: actions/upload-artifact@v2
          with:
            name: workload-plan
            path: ${{ env.WORKING_DIRECTORY }}/workload.tfplan
            retention-days: 1
        - name: 'Azure CLI logout'
          uses: azure/CLI@v1
          with:
            inlineScript: |
              az logout
              az cache purge
              az account clear
  apply:
    name: 'apply infrastructure'
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@v2
      - name: 'Download Plan'
        uses: actions/download-artifact@v2
        with:
          name: workload-plan
      - name: 'Move Plan'
        run: mv ./workload.tfplan ${{ env.WORKING_DIRECTORY }}
      - name: 'Delete Plan from Repo'
        uses: geekyeggo/delete-artifact@v1
        with:
          name: workload-plan
          failOnError: false
      - name: 'Azure Login'
        uses: azure/login@v1
        with:
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
      - name: 'Get Deployer Secrets'
        id: get-deployer-secret
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ secrets.DEPLOYER_KEY_VAULT }}
          secrets: 'adls2-demo-eastus2-deployer, tfadls2ed-access-key'
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
      - name: 'Terraform Init'
        env: 
          TF_CLI_ARGS_init: "-backend-config='resource_group_name=${{env.REMOTE_STATE_RG}}' -backend-config='storage_account_name=${{env.REMOTE_STATE_SA}}' -backend-config='container_name=${{env.REMOTE_STATE_CONTAINER}}' -backend-config='key=${{env.REMOTE_STATE_KEY}}'"
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfadls2ed-access-key }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform init
      - name:  'Terraform Apply'
        env:
          ARM_CLIENT_SECRET: ${{ steps.get-deployer-secret.outputs.adls2-demo-eastus2-deployer }}
          ARM_ACCESS_KEY: ${{ steps.get-deployer-secret.outputs.tfadls2ed-access-key }}
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: terraform apply -auto-approve "./workload.tfplan"
      - name: 'Azure CLI logout'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear